name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  workflow_run:
#    workflows: [ "Playwright UI Tests (JUnit)" ]
#    types:
#      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Verify Maven installation
        run: mvn -version

      - name: Get product name and version
        run: |
          echo "VERSION=$(mvn help:evaluate -q -DforceStdout -D"expression=project.version")" >> $GITHUB_ENV
          echo "NAME=$(mvn help:evaluate -q -DforceStdout -D"expression=project.name")" >> $GITHUB_ENV

      - name: Build Java project with Maven
        run: |
          mvn dependency:go-offline -Pproduction
          mvn clean package -DskipTests -Pproduction

      - name: Build and push Docker image
        run: |
          docker build -t fredpena/${NAME}:lastest .
          docker push fredpena/${NAME}:lastest

      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            pwd
            cd /usr/local/app
            docker compose pull
            docker compose up -d